branches: [master]
pipeline:
  build:
    image: lachlanevenson/k8s-helm
    commands:
      - helm init --client-only
      - helm package drone
      - helm repo index .
  publish:
    image: alpine
    commands:
      - ls
