branches: [master]
pipeline:
  build:
    image: lachlanevenson/k8s-helm
    commands:
      - helm init --client-only
      - mkdir charts
      - helm package -d charts drone
      - (cd charts && helm repo index .)
  publish:
    image: alpine
    commands:
      - ls
