branches: [master]
pipeline:
  build:
    image: lachlanevenson/k8s-helm
    commands:
      - helm init --client-only
      - mkdir charts
      - helm package -d charts drone
      - helm package -d charts emq
      - helm package -d charts hanami
      - mv index.html charts/index.html
      - cd charts
      - helm repo index .
  publish:
    image: node
    commands:
      - npm install surge
      - ./node_modules/.bin/surge --version
      - ./node_modules/.bin/surge --project ./charts --domain charts.127labs.com
    secrets: [surge_login, surge_token]
