{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ template "fullname" . }}-tls
{{- end }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "fullname" . }}
            servicePort: {{ .Values.env.EMQ_DASHBOARD__LISTENER__HTTP }}
{{- end -}}
